package MCDataCode.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Command = 0;
  public static final int CommandGamemode = 1;
  public static final int CommandSay = 2;
  public static final int Function = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5e2d0034c7544833L, 0xa8c206f62c92f462L);
    builder.put(0x77b4c904d635a782L, Command);
    builder.put(0x77b4c904d635a790L, CommandGamemode);
    builder.put(0x77b4c904d635a78dL, CommandSay);
    builder.put(0x77b4c904d635a77fL, Function);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
