package MCDataCode.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCommand = createDescriptorForCommand();
  /*package*/ final ConceptDescriptor myConceptCommandGamemode = createDescriptorForCommandGamemode();
  /*package*/ final ConceptDescriptor myConceptCommandSay = createDescriptorForCommandSay();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptMainStructure = createDescriptorForMainStructure();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCommand, myConceptCommandGamemode, myConceptCommandSay, myConceptFunction, myConceptMainStructure);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Command:
        return myConceptCommand;
      case LanguageConceptSwitch.CommandGamemode:
        return myConceptCommandGamemode;
      case LanguageConceptSwitch.CommandSay:
        return myConceptCommandSay;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.MainStructure:
        return myConceptMainStructure;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MCDataCode", "Command", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a782L);
    b.class_(false, true, false);
    b.origin("r:96fe2abe-f504-41a5-b0b8-2978403723e4(MCDataCode.structure)/8625740208932235138");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCommandGamemode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MCDataCode", "CommandGamemode", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a790L);
    b.class_(false, false, false);
    b.super_("MCDataCode.structure.Command", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a782L);
    b.origin("r:96fe2abe-f504-41a5-b0b8-2978403723e4(MCDataCode.structure)/8625740208932235152");
    b.version(2);
    b.prop("gamemode", 0x77b4c904d635a791L, "8625740208932235153");
    b.alias("gamemode");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCommandSay() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MCDataCode", "CommandSay", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a78dL);
    b.class_(false, false, false);
    b.super_("MCDataCode.structure.Command", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a782L);
    b.origin("r:96fe2abe-f504-41a5-b0b8-2978403723e4(MCDataCode.structure)/8625740208932235149");
    b.version(2);
    b.prop("message", 0x77b4c904d635a78eL, "8625740208932235150");
    b.alias("say");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MCDataCode", "Function", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a77fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:96fe2abe-f504-41a5-b0b8-2978403723e4(MCDataCode.structure)/8625740208932235135");
    b.version(2);
    b.aggregate("cmds", 0x77b4c904d635a789L).target(0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a782L).optional(true).ordered(true).multiple(true).origin("8625740208932235145").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMainStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MCDataCode", "MainStructure", 0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d6391209L);
    b.class_(false, false, true);
    b.origin("r:96fe2abe-f504-41a5-b0b8-2978403723e4(MCDataCode.structure)/8625740208932459017");
    b.version(2);
    b.aggregate("functions", 0x77b4c904d639120aL).target(0x5e2d0034c7544833L, 0xa8c206f62c92f462L, 0x77b4c904d635a77fL).optional(true).ordered(true).multiple(true).origin("8625740208932459018").done();
    b.alias("main");
    return b.create();
  }
}
